### ISSUE TITLE
iOS13/Xcode11 ?

### ISSUE THREAD

**Issue by jhjulkun** [IndoorAtlas/ios-sdk-swift-examples#29]
Hi

Have you guys tried the example using iOS13/Xcode11 ?

I just downloaded the example, and after adding this to Info.plist it at least runs. `<key>NSBluetoothAlwaysUsageDescription</key>
<string>Need Bluetooth to work.</string>`

But you get these error messages:
nehelper sent invalid result code [1] for Wi-Fi information request
(after googling, seems like Apple changed something with regards to wifi)

However, I then tried the example on an iOS12.4 device, 
and the 'Map View' works, but the ImageView just shows a 'TraceID' at the top, 
but nothing else.

I have mapped the area using the MapCreator2 
(on a Pixel/Android10 which also complain about wifi issues). 

The floor plan does show up on https://app.indooratlas.com/locations so I think MapCreator2 worked, but since nothing shows up in iOS I'm not positive.

Thanks

**Comment by matti-ida** [comment]
Hi,

thanks for the report. This should be fixed by https://github.com/IndoorAtlas/ios-sdk-swift-examples/commit/caef5bbb452e8012b82315f5cd01f6b4cd4ea7b1

The Wi-Fi error should be harmless otherwise, we will fix it for our next SDK release (3.1.1).

Please check our knowledge base at https://indooratlas.freshdesk.com/support/home
Troubleshooting check list is at https://indooratlas.freshdesk.com/support/solutions/folders/36000173652
